version: 2.1

jobs:
  hello-and-pass-or-fail:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Hello, world!"
      - run:
          name: Wait for ten minutes
          command: |
            for i in {1..600}; do
              echo "$i seconds elapsed"
              sleep 1
            done
      - run: |
          if [ $((RANDOM % 20)) -eq 0 ]
          then
            exit 1
          fi

workflows:
  say-hello-workflow:
    jobs: 
      - hello-and-pass-or-fail:
        filters:
          branches:
            only: 
              - main
