version: 2.1

jobs:
    filters:
      branches:
        only: main
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Hello, world!"
      - run:
          name: Wait for one minute
          command: |
            for i in {1..60}; do
              echo "$i seconds elapsed"
              sleep 1
            done
      - run: |
          if [ $((RANDOM % 20)) -eq 0 ]
          then
            exit 1
          fi

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
