name: Check Circle Status
on:
  pull_request:
    types: [queue]
jobs:
  merge-queue:
    runs-on: ubuntu-latest
    steps:
      - name: Set env vars
        run: | 
          export CIRCLE_TOKEN={**secret**}
          export API_URL={https://circleci.com/api/v2/insights/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/workflows?branch=main}
      - name: Check previous Circle run status
        id: get_status
        run: |
          PREV_MERGE_STATUS=$(curl --request GET -- url ${API_URL} --header "Circle-Token: $CIRCLE_TOKEN")
          echo "::set-output name=status::$PREV_MERGE_STATUS"
      - name: Proceed and merge current PR
        if: ${{ steps.get_status.outputs.status == 'success' || steps.get_status.outputs.status  == 'skipped' }}
        run: exit 0
      - name: Keep waiting and re-check status every x minutes
        if: ${{ steps.get_status.outputs.status != 'success' && steps.get_status.outputs.status  != 'skipped' }}
        # do a thing
        run: exit 1
    #   - name: Timeout
    #     if: exceeded 60 minutes, etc
    #     run: exit 1
