name: Test run circle api calls
on: [pull_request]
jobs:
  check-circle-status:
    runs-on: ubuntu-latest
    steps:
      - name: Set env vars
      run: | 
        export CIRCLE_TOKEN={b044f96d90b2f2b5fadad71852d98603673a7357}
        export API_URL={https://circleci.com/api/v2/project/gh/jfu-test-org/test-queues/workflows?branch=main}
      - name: Check previous Circle run status
        id: get_status
        run: |
          PREV_MERGE_STATUS=$(curl --request GET -- url ${API_URL} --header "Circle-Token: $CIRCLE_TOKEN")
          echo "::set-output name=status::$PREV_MERGE_STATUS"
