name: Fail 20% of the time
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run for 20 seconds
      run: sleep 20
    - name: Fail 20% of the time
      run: |
        if [ $((RANDOM % 20)) -eq 0 ]
        then
          exit 1
        fi
