name: Wait 10 minutes and fail 20% of the time
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run for 10 minutes
      run: |
        for i in {1..600}; do
          echo "$i seconds elapsed"
          sleep 1
        done
    # - name: Fail 20% of the time
    #   run: |
    #     if [ $((RANDOM % 20)) -eq 0 ]
    #     then
    #       exit 1
    #     fi
    - name: fail
      run: exit 1
