name: Wait 3 minutes and succeed
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run for 3 minutes
      run: |
        for i in {1..180}; do
          echo "$i seconds elapsed"
          sleep 1
        done
    # - name: Fail 20% of the time
    #   run: |
    #     if [ $((RANDOM % 20)) -eq 0 ]
    #     then
    #       exit 1
    #     fi
    - name: succeed
      run: exit 0
